apiVersion: v1
kind: Pod
metadata:
  name: fortune-config
spec:
  containers:
  - name: fortune-app
    image: luksa/fortune:args
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - name: nginx-app
    image: nginx:alpine
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d 
  volumes:
  - name: html
    emptyDir: {} 
  - name: config
    configMap:
      name: fortune-config
