apiVersion: v1
kind: Pod
metadata:
  name: fortune2s
spec:
  containers:
  - name: fortune2s
    image: snehil0801/fortune-image:args
    args:
    - "2"
    volumeMounts:
    - mountPath: /var/htdocs
      name: html
  volumes:
  - emptyDir: {}
    name: html
