apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
spec:
  containers:
  - name: pod-with-configmap
    image: luksa/fortune:env
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
  volumes:
  - name: html
    emptyDir: {}
     
    
  
