apiVersion: v1
kind: Pod
metadata:
  name: podwithpvc
  labels:
    app: pod-with-pvc
spec:
  containers:
  - name: pvc-container
    image: mongo
    volumeMounts:
    - mountPath: /data/db
      name: mongodb-v1
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-v1
    persistentVolumeClaim:
      claimName: mongodb-pvc
