apiVersion: v1
kind: Pod
metadata:
  name: liveness-prob-pod
  labels: 
    pod-name: liveness-prob-http-get
spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: snehil-node-app
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8080
