apiVersion: v1
kind: Pod
metadata:
  name: snehil-node
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image: snehil0801/snehil-node
    name: snehil-node-selector
    ports:
    - containerPort: 8080
      protocol: TCP
