apiVersion: v1
kind: ReplicationController
metadata:
  name: snehil-node-rc
spec:
  replicas: 3
  selector:
    app: snehil-node
  template:
    metadata:
      labels:
        app: snehil-node
    spec:
      containers:
      - image: snehil0801/snehil-node
        name: snehil-node-app
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080
          protocol: TCP
