apiVersion: v1
kind: Pod
metadata:
  name: fortune-creds-images
spec:
  containers:
  - name: fortune-app
    image: snehil0801/fortune-image:args
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  volumes:
  - name: html
    emptyDir: {}
  imagePullSecrets:
  - name: mydockercreds
